// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfrhAW3PO6eOaOBqtEJuFFa8yfTt6pHR8',
    appId: '1:186906050704:web:cca76456f0304a62695815',
    messagingSenderId: '186906050704',
    projectId: 'smart-schedule-app-64439',
    authDomain: 'smart-schedule-app-64439.firebaseapp.com',
    storageBucket: 'smart-schedule-app-64439.firebasestorage.app',
    measurementId: 'G-WVVNYXB6E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBiWWmx3MTc1hfQQNGwkYblEF7tNPLL9c',
    appId: '1:186906050704:android:50d9de3e3ca8f94b695815',
    messagingSenderId: '186906050704',
    projectId: 'smart-schedule-app-64439',
    storageBucket: 'smart-schedule-app-64439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-7lKgc9F7Wph7sUZHw7qWhX7UhKL44LA',
    appId: '1:186906050704:ios:106ae5bfe635c717695815',
    messagingSenderId: '186906050704',
    projectId: 'smart-schedule-app-64439',
    storageBucket: 'smart-schedule-app-64439.firebasestorage.app',
    iosBundleId: 'com.example.smartClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-7lKgc9F7Wph7sUZHw7qWhX7UhKL44LA',
    appId: '1:186906050704:ios:106ae5bfe635c717695815',
    messagingSenderId: '186906050704',
    projectId: 'smart-schedule-app-64439',
    storageBucket: 'smart-schedule-app-64439.firebasestorage.app',
    iosBundleId: 'com.example.smartClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfrhAW3PO6eOaOBqtEJuFFa8yfTt6pHR8',
    appId: '1:186906050704:web:777fad9338a4b700695815',
    messagingSenderId: '186906050704',
    projectId: 'smart-schedule-app-64439',
    authDomain: 'smart-schedule-app-64439.firebaseapp.com',
    storageBucket: 'smart-schedule-app-64439.firebasestorage.app',
    measurementId: 'G-88SQCLMQ6H',
  );
}
